services:
  chatbot-fitbridge:
    image: rutkre/fitbridge-chatbot:latest
    restart: unless-stopped
    expose:
      - "8002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-fitbridge.rule=Host(`chatbot-fitbridge.${DOMAIN_NAME}`)"
      - "traefik.http.routers.chatbot-fitbridge.entrypoints=websecure"
      - "traefik.http.routers.chatbot-fitbridge.tls=true"
      - "traefik.http.routers.chatbot-fitbridge.tls.certresolver=myresolver"
      - "traefik.http.routers.chatbot-fitbridge.priority=50"
      - "traefik.http.services.chatbot-fitbridge.loadbalancer.server.port=8002"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${STACKS_VOLUME_PATH}/fitbridge/chatbot.env:/usr/src/app/.env
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "2"
        loki-max-backoff: "900ms"
        loki-timeout: "1s"
        keep-file: "true"
    networks:
      - proxy
  api-fitbridge:
    image: rutkre/fitbridge-be:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8003
      - ConnectionStrings__FitbridgeDb=Host=postgres;Port=5432;Database=FitBridge;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Trust Server Certificate=true
    expose:
      - "8003"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-fitbridge.rule=Host(`api-fitbridge.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api-fitbridge.entrypoints=websecure"
      - "traefik.http.routers.api-fitbridge.tls=true"
      - "traefik.http.routers.api-fitbridge.tls.certresolver=myresolver"
      - "traefik.http.routers.api-fitbridge.priority=50"
      - "traefik.http.routers.api-fitbridge.middlewares=chain-api-with-websocket@file"
      - "traefik.http.services.api-fitbridge.loadbalancer.server.port=8003"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${STACKS_VOLUME_PATH}/fitbridge/appsettings.json:/app/appsettings.json
      - ${STACKS_VOLUME_PATH}/fitbridge/fitbridge-firebase-admin-sdk.json:/app/fitbridge-firebase-admin-sdk.json
      - ${STACKS_VOLUME_PATH}/fitbridge/push_noti_cert.p8:/app/push_noti_cert.p8
    deploy:
      mode: replicated
      replicas: 3
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "2"
        loki-max-backoff: "900ms"
        loki-timeout: "1s"
        keep-file: "true"
    depends_on:
      - chatbot-fitbridge
    networks:
      - postgres
      - proxy
      - redis
networks:
  postgres:
    external: true
  proxy:
    external: true
  redis:
    external: true
